#!/usr/bin/env bash
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#

read -r RICETHEME <"$HOME"/.config/bspwm/.rice
export RICETHEME
PATH="$HOME/.config/bspwm/scripts:$PATH"
rice_dir="$HOME/.config/bspwm/rices/$RICETHEME"
export XDG_CURRENT_DESKTOP='bspwm'

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1
bspc rule -a lf -o state=floating
#nohup oneko -dog &

#  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝
#feh --bg-fill /home/florin/Pictures/beautiful.jpg

#Default 1 monitor with 6 workspaces
INTERNAL_MONITOR="DisplayPort-1"
EXTERNAL_MONITOR="DisplayPort-2"
if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
	bspc monitor "$EXTERNAL_MONITOR" -d '' '' '' ''
	bspc monitor "$INTERNAL_MONITOR" -d '' '' '' ''
	bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
else
	bspc monitor "$INTERNAL_MONITOR" -d '' '' '' '' '' '' '' ''
fi
# create workspaces
# create workspaces
xrandr --output DisplayPort-2 --mode 1920x1080 --rate 240.00 --pos 0x0
xrandr --output DisplayPort-1 --mode 2560x1440 --rate 240.00 --pos 1920x0

## For two or three monitors configuration see https://github.com/gh0stzk/dotfiles/wiki/Two-or-more-monitors-setup

#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠╩╗╚═╗╠═╝║║║║║║  ║  ║ ║║║║╠╣ ║║ ╦
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝

bspc config external_rules_command "$HOME"/.config/bspwm/scripts/ExternalRules

bspc config window_gap 6
bspc config split_ratio 0.51
bspc config single_monocle true
bspc config borderless_monocle false

bspc config gapless_monocle false

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_motion_interval 5
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#bspc wm --adopt-orphans
bspc rule -a scratch sticky=on state=floating focus=on

#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩

# Set system vars for polybar
. SetSysVars

# Terminate already running polybar, stalonetray, sxhkd and dunst instances
processes=("sxhkd" "polybar" "dunst" "eww.*bar")

for process in "${processes[@]}"; do
	if pgrep -f "$process"; then
		pkill -f "$process" >/dev/null
		sleep 0.25
	fi
done

# Load bspwm conf, colors, dunst, bars and/or eww widgets
. "${rice_dir}"/Theme.sh

# Reload sxhkd daemon
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc &
sxhkd -c "$HOME"/.config/bspwm/sxhkdrc2 &

# Launch picom // If you have old hardware or encounter problems
# uncomment the picom "--legacy-backends" line and comment the current one.
#pidof -q picom || { picom --config "$HOME"/.config/bspwm/picom.conf & }
pidof -q picom || { picom --legacy-backends --config "$HOME"/.config/bspwm/picom.conf & }

# Launch dunst notification daemon
dunst -config "$HOME"/.config/bspwm/dunstrc &
greenclip daemon &

# Launch eww daemon
pidof -q eww || { eww -c "$HOME"/.config/bspwm/eww daemon & }

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# Fix cursor
    xsetroot -cursor_name left_ptr
