// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "6f3bd673-a0eb-4acd-9d37-78c606817409");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1710614014);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1710614070);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{17f6c64a-6f97-4c32-944f-64700448c89c}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.engagement.fxa-toolbar-menu-button.has-used", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1710614011);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 142);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8b81ed7a-f335-4d61-bdab-173e0d7aad9e}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1710614013);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1710614014422");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1710635614422");
user_pref("browser.search.region", "DE");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1710614070");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20240304205002");
user_pref("browser.startup.homepage_override.mstone", "123.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1710614070);
user_pref("browser.topsites.contile.cacheValidFor", 11109);
user_pref("browser.topsites.contile.cachedTiles", "[{\"id\":74357,\"name\":\"Amazon\",\"url\":\"https://www.amazon.de/?tag=admpdesktopde-21&ref=pd_sl_2cb9ab21ca7dadc7996a03c4b0f1912d557165ac5e5413e50be115bd&mfadid=adm\",\"click_url\":\"https://bridge.sfo1.ap01.net/ctp?version=16.0.0&ci=1710611834782.12791&key=1710611834400800000.1&ctag=pd_sl_2cb9ab21ca7dadc7996a03c4b0f1912d557165ac5e5413e50be115bd\",\"image_url\":\"https://contile-images.services.mozilla.com/obgoOYObjIFea_bXuT6L4LbBJ8j425AD87S1HMD3BWg.9991.jpg\",\"image_size\":200,\"impression_url\":\"https://imp.mt48.net/static?id=7RHzfOIXjFEYsBdvIpkX4ZlW4QlX1pfk4pbW1pbWfpbW7ReNxR3UIG8zInwYIFIVs9eYiGINHrwkiFXwxYIZjF8XgClWfC2X7R4dHQ8zJnErj%3DcO7R4dHQfz4Z2Z4CxnHG3Z5FwqgCfX1p8d4Cxr1BINI9HuiF2z4Z2Z4CxnHmcux%3DcvImauiF2zfQlW1CbZ7ncqIr7VjGbuiF2zfCfk1CfXfClnj9wWIBdvIpkY7R4TJr2uJREuHnEYgClnHr7wHG3vjnDuiF2z4Z2d7ReTHF4wJFEUjtdvIpkXfpbr\"},{\"id\":74985,\"name\":\"Otto\",\"url\":\"https://partnerprogramm.otto.de/trck/eclick/df78a463815f994db2216e95a76a35b3?subid=1710611834400800000&mfadid=adm\",\"click_url\":\"https://bridge.sfo1.admarketplace.net/ctp?version=16.0.0&ci=1710611834782.12791&key=1710611834400800000.2&ctag=1710611834400800000\",\"image_url\":\"https://contile-images.services.mozilla.com/ELjwhjtjrvbTZP-8MFWEloeHBDeP_e9NY1lWqDRFJJM.14810.jpg\",\"image_size\":200,\"impression_url\":\"https://imp.mt48.net/static?id=7RHzfOIXjFEYsBdvIpkX4ZlW4QlX1pfk4pbW1pbWfpbW7ReNxR3UIG8zInwYIFIVs9eYiGINHrwkiFXwxYIZjF8XgClWfC2X7R4dHQ8zJnErj%3DcO7R4dHQfz4Z2%2B1pDnHG3Z5FwqgCfX1p8d4Cxr1BINI9HuiF2z4Z2%2B1pDnHmcux%3DcvImauiF2zfQ8WfpHd7ncqIr7VjGbuiF2zfCDk4ZxmfCDnj9wWIBdvIpkY7R4TJr2uJREuHnEYgC8nHr7wHG3vjnDuiF2zfQld4BIWJ%3DcQIFdwJR2uiF2zfCbW4Wyy\"}]");
user_pref("browser.topsites.contile.lastFetch", 1710614070);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1710614012764");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "123.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "DE");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "6d8e5452da734cef8bdc3bb95c5629da");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20240304205002");
user_pref("extensions.lastAppVersion", "123.0.1");
user_pref("extensions.lastPlatformVersion", "123.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"ef9efefd-3cb5-4853-9f96-a7782aec95b2\",\"pictureinpicture@mozilla.org\":\"e3ac3e95-2bac-42fa-b5ad-8e5201fb3231\",\"screenshots@mozilla.org\":\"71fb2004-ac74-45ba-bdd1-344cac664db0\",\"webcompat-reporter@mozilla.org\":\"2091d06a-a4a1-437e-b054-29fe978c9d65\",\"webcompat@mozilla.org\":\"cadb9081-2da0-4e39-810f-94d36ac8756c\",\"default-theme@mozilla.org\":\"a4297127-ed17-4a82-9691-2fb08d8d9ebf\",\"addons-search-detection@mozilla.com\":\"2b367d9b-863a-4afe-acf8-b0e85c0e935d\",\"google@search.mozilla.org\":\"9521b2f7-338c-41e3-98b1-f21767a24784\",\"wikipedia@search.mozilla.org\":\"5fbe669f-2fd3-48bd-bacc-cb5ffd13de4e\",\"bing@search.mozilla.org\":\"f0643c13-158f-469d-944e-3dda8cbe0402\",\"ddg@search.mozilla.org\":\"f555c5a8-179c-4189-bfba-68a20547b111\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("memory.phc.enabled", true);
user_pref("messaging-system-action.showEmbeddedImport", true);
user_pref("nimbus.syncdefaultsstore.fxaButtonVisibility", "{\"slug\":\"mozillaaccounts-toolbar-button-default-visibility-existing-user\",\"branch\":{\"slug\":\"treatment-a\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"fxaButtonVisibility\"},\"features\":null},\"active\":true,\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"MozillaAccounts toolbar button default visibility rollout\",\"userFacingDescription\":\"This experiment measures the impact of showing the Firefox Accounts toolbar button by default for signed-out users.\",\"lastSeen\":\"2024-03-16T18:33:32.837Z\",\"featureIds\":[\"fxaButtonVisibility\"],\"prefs\":[{\"name\":\"identity.fxaccounts.toolbar.defaultVisible\",\"branch\":\"user\",\"featureId\":\"fxaButtonVisibility\",\"variable\":\"boolean\",\"originalValue\":null}],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.fxaButtonVisibility.boolean", true);
user_pref("nimbus.syncdefaultsstore.phc", "{\"slug\":\"phc-rollout\",\"branch\":{\"slug\":\"rollout\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"phc\"},\"features\":null},\"active\":true,\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"PHC Rollout\",\"userFacingDescription\":\"Roll out the Probabilistic Heap Checker in Firefox Release.\",\"lastSeen\":\"2024-03-16T18:33:32.907Z\",\"featureIds\":[\"phc\"],\"prefs\":[{\"name\":\"memory.phc.enabled\",\"branch\":\"user\",\"featureId\":\"phc\",\"variable\":\"phcEnabled\",\"originalValue\":null}],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.phc.phcEnabled", true);
user_pref("nimbus.syncdefaultsstore.pocketNewtab", "{\"slug\":\"rollout-of-share-of-voice-for-sponsored-topsites\",\"branch\":{\"slug\":\"control\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"pocketNewtab\"},\"features\":null},\"active\":true,\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Rollout of Share-of-Voice for Sponsored TopSites\",\"userFacingDescription\":\"Rollout of the Share-of-Voice feature to dynamically manage ad inventory on the NewTab page.\",\"lastSeen\":\"2024-03-16T18:33:32.852Z\",\"featureIds\":[\"pocketNewtab\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.pocketNewtab.topSitesContileSovEnabled", true);
user_pref("nimbus.syncdefaultsstore.upgradeDialog", "{\"slug\":\"upgrade-spotlight-rollout\",\"branch\":{\"slug\":\"treatment\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"upgradeDialog\"},\"features\":null},\"active\":true,\"experimentType\":\"rollout\",\"source\":\"rs-loader\",\"userFacingName\":\"Upgrade Spotlight Rollout\",\"userFacingDescription\":\"Experimenting on onboarding content when you upgrade Firefox.\",\"lastSeen\":\"2024-03-16T18:33:32.860Z\",\"featureIds\":[\"upgradeDialog\"],\"prefs\":[],\"isRollout\":true}");
user_pref("nimbus.syncdefaultsstore.upgradeDialog.enabled", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "8618b47d-cf2f-475d-9c97-442efe1fa4b9");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("toolkit.startup.last_success", 1710614069);
user_pref("toolkit.telemetry.cachedClientID", "d314ad6a-13ad-4936-9a84-400363380bfd");
user_pref("toolkit.telemetry.previousBuildID", "20240304205002");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
