# (Decay, decayce variant) Color scheme for z0mbi3 Rice

# Default colors
[colors.primary]
background = "#0d0f18"
foreground = "#a5b6cf"

# Cursor colors
[colors.cursor]
cursor = "#a5b6cf"
text = "#0d0f18"

# Normal colors
[colors.normal]
black = "#3d414f"
blue = "#86aaec"
cyan = "#93cee9"
green = "#90ceaa"
magenta = "#c296eb"
red = "#dd6777"
white = "#cbced3"
yellow = "#ecd3a0"

# Bright colors
[colors.bright]
black = "#3d414f"
blue = "#86aaec"
cyan = "#93cee9"
green = "#90ceaa"
magenta = "#c296eb"
red = "#dd6777"
white = "#cbced3"
yellow = "#ecd3a0"
